### ISSUE TITLE
trampoline: missing environment variables populated from dev-rel-resources

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/docker-ci-helper#39]
With trampoline@v1 there were some environment variables and secrets populated from the `cloud-devrel-kokoro-resources` folder. For instance, `AUTOML_PROJECT_ID` in the automl project.

How do we allow teams to set their own environment variables in v1?

**Comment by tmatsuo** [comment]
Trampoline V2 doesn't pass all the variables into the container. 

Options are
1. allow environment variables in the rc file
2. Set the env var in the container

**Comment by bcoe** [comment]
@tmatsuo I think I might be able to purpose the secret manager work we did recently, let me try an experiment.

**Comment by bcoe** [comment]
was able to address this using our new approach with secret manager:

https://github.com/googleapis/nodejs-automl/blob/1ef9df7927fa6dfcb5292412ea0480c64e0f95ee/.kokoro/pre-samples-test.sh
